### ISSUE TITLE
This repo is not driving the live website

### ISSUE THREAD

**Issue by hlapp** [phylotastic/phylotastic.github.io#4]
The live website appears to be served out of www.cs.nmsu.edu, not Github, and it doesn't seem to serve the complete contents of this repo, nor does it seem to get updated regularly. For example, the changes from the most recent commit (8016b3cbc6fe1cbb7ebe90bf6155634a6658a2c4) aren't on the live site. The markdown and other documents in the `docs/` directory result in 404s. Likewise, the TNRS ontology terms served out from `terms/` result in a 404 too, which means the ontology is unretrievable from its published URI.

Any reason not to switch back to using Github pages hosting and let Github do the work?

**Comment by bomeara** [comment]
FWIW, I agree with Hilmar on this. Moving to github will make it more restful, too (i.e., can't have URL linking directly to our grant, for example).

**Comment by arlin** [comment]
Thanks for bringing this up.  I never liked the non-RESTful behavior.  I don't know why we are doing it this way.  I'm putting it on the agenda for the next meeting.
