### ISSUE TITLE
update content to reflect NSF project outcomes

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic.github.io#5]
*About* 
- remove emphasis on hackathons; remove legacy content
- change emphasis to NSF project

*Demos*
- add link (top) to portal with description 
- add link (next) to mobile app with text or separate page explaining how to get it
- remove "topology server" example 
- put remaining examples in "Legacy (may not work)"

*Web services* 
- remove or hide all existing services
- add descriptions and links to our new services 

*Wiki* 
- link to https://github.com/phylotastic/phylotastic/wiki

*Code* 
- nothing needs to be changed

**Comment by arlin** [comment]
I will do the "about" part

**Comment by arlin** [comment]
I updated "About" (about.html) and fixed the link to the wiki in "index.html".  

@hdliv, the rest of it is up to you, according to our plan above.

**Comment by hdliv** [comment]
updated according to the plan

**Comment by hdliv** [comment]
@arlin I didnt understand.  Did you update my edits?

**Comment by arlin** [comment]
on the "demos" page, the "legacy" section dominates the page.  This material is relatively unimportant and should be in small font or tiny font compared to the two current demos, the portal and the mobile app.  

<img width="663" alt="screen shot 2016-09-12 at 1 05 34 pm" src="https://cloud.githubusercontent.com/assets/1659198/18445078/dd0d7064-78e9-11e6-9e5c-e5a2f004a6bd.png">

**Comment by arlin** [comment]
the "web services" list does not look enough like a list.  Some of the names are too long and they wrap.  Note that, unlike for the demos page, we don't expect many users to actually use these services given the current stage of the project.  What we want to accomplish with this page is to advertise to the world that our project is developing *many* useful services.  So, I would recommend. 
* use the "demolist" class used on the demos page
* add a brief description of each service.  

<img width="659" alt="screen shot 2016-09-12 at 1 28 43 pm" src="https://cloud.githubusercontent.com/assets/1659198/18445716/e774a240-78ec-11e6-80fa-153cfade672b.png">

**Comment by hdliv** [comment]
for the list I am now using: <ul style="list-style-type:circle"><font size= "-1">

**Comment by arlin** [comment]
@hdliv, we talked about this one today.  The list of names and descriptions is already available in github, in the web services docs repository.  Just copy and paste this into the services.html page and that will be fine.  We don't need to spend a lot of time on this now, but we want the content to be (superficially) complete and well formatted.

**Comment by hdliv** [comment]
@arlin as for services, this has been pushed.  I updated a little of the working on demos and made the legacy smaller.  Do you want to make the figure or should I?

**Comment by arlin** [comment]
I decided to hide the legacy stuff.  DateLife isn't legacy so it stays in the main section.  

As for the figure, this is not a high priority.  I'm not going to get to it this week.  I would suggest not to spend time on it.

**Comment by hdliv** [comment]
@arlin OK
